"""Shared research pipeline defaults (live data, maximum practical history)."""

from __future__ import annotations

# ~3 years of earnings events per symbol (4 quarterly reports × ~3 years).
EARNINGS_RECENT_DAYS = 1095
EARNINGS_LIMIT_PER_SYMBOL = 24

# Default news backfill window (override with NEWS_BACKFILL_DAYS in .env).
NEWS_BACKFILL_DAYS = 730
NEWS_INGEST_HOURS_BACK = 24 * 730

# EODHD earnings API batch size (URL length safety).
EARNINGS_BATCH_CHUNK = 40

# Backtest defaults
DEFAULT_TRAIN_RATIO = 0.7
DEFAULT_ROUND_TRIP_COST_BPS = 10.0
DEFAULT_MIN_CONFIDENCE = 0.15
DEFAULT_MODEL_MIN_CONFIDENCE = 0.50
DEFAULT_MAX_POSITION_WEIGHT = 1.0
DEFAULT_MIN_POSITION_WEIGHT = 0.25
WALK_FORWARD_MIN_TRAIN_EVENTS = 48
WALK_FORWARD_TEST_CHUNK = 12

DEFAULT_TOP_K_LONG_PER_FOLD = 1
DEFAULT_TOP_K_SHORT_PER_FOLD = 1
DEFAULT_TARGET_TRADES_PER_MONTH = 3.0
DEFAULT_HOLDOUT_DAYS = 90
DEFAULT_PERMUTATION_IMPORTANCE_REPEATS = 20
DEFAULT_PERMUTATION_IMPORTANCE_SEED = 42
